- name: Insert dummy posts 
  community.mysql.mysql_query:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: "{{ mysql_user }}"
    login_password: "{{ mysql_pass }}"
    login_db: "{{ mysql_database }}"
    query: "{{ lookup('template', 'insert_dummy_posts.sql.j2') }}"
  vars:
    author: "{{ hostvars[inventory_hostname]['owner'] }}"
