---
- hosts: all
  gather_facts: yes
  become: yes
  become_user: root
  tasks:
    - ansible.builtin.import_role:
        name: setup_apache_and_php
    - ansible.builtin.import_role:
        name: setup_mysql_db
    - ansible.builtin.import_role:
        name: deploy_website
